# Generated by Django 3.1.5 on 2021-10-11 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('in_ucsc', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iterations_right', models.IntegerField(blank=True, default=0, null=True)),
                ('iterations_left', models.IntegerField(blank=True, default=0, null=True)),
                ('igv_screenshot', models.BooleanField(default=False)),
                ('browser', models.BooleanField(default=True)),
                ('contig_size', models.IntegerField(blank=True, null=True)),
                ('contig_extension_size', models.IntegerField(blank=True, null=True)),
                ('reference_prefix_to_map_size', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('technology', models.CharField(choices=[('pb', 'PacBio'), ('hifi', 'Oxford Nanopore'), ('ont', 'PacBio HiFi')], max_length=4)),
                ('mappings', models.ManyToManyField(blank=True, to='clusters.Mapping')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iterations_right', models.IntegerField(blank=True, default=0, null=True)),
                ('iterations_left', models.IntegerField(blank=True, default=0, null=True)),
                ('igv_screenshot', models.BooleanField(default=False)),
                ('browser', models.BooleanField(default=True)),
                ('contig_size', models.IntegerField(blank=True, null=True)),
                ('contig_extension_size', models.IntegerField(blank=True, null=True)),
                ('reference_prefix_to_map_size', models.IntegerField(blank=True, null=True)),
                ('start_name', models.CharField(max_length=50)),
                ('assembly_type', models.CharField(choices=[('U', 'From unique sequence'), ('C', 'From cluster of sequences')], max_length=1)),
                ('mappings', models.ManyToManyField(blank=True, to='clusters.Mapping')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='clusters.sample')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
