# Generated by Django 4.1 on 2022-08-16 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("in_ucsc", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iterations", models.IntegerField(blank=True, null=True)),
                ("igv_screenshot", models.BooleanField(null=True)),
                ("browser", models.BooleanField(null=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "technology",
                    models.CharField(
                        choices=[
                            ("pb", "PacBio"),
                            ("hifi", "Oxford Nanopore"),
                            ("ont", "PacBio HiFi"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "mappings",
                    models.ManyToManyField(blank=True, to="clusters.reference"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Contig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iterations", models.IntegerField(blank=True, null=True)),
                ("igv_screenshot", models.BooleanField(null=True)),
                ("browser", models.BooleanField(null=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "assembly_type",
                    models.CharField(
                        choices=[
                            ("U", "From unique sequence"),
                            ("C", "From cluster of sequences"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "mappings",
                    models.ManyToManyField(blank=True, to="clusters.reference"),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="samples",
                        to="clusters.sample",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
