# Generated by Django 3.1.5 on 2021-01-15 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('start_name', models.CharField(max_length=50)),
                ('number_max', models.IntegerField()),
                ('assembly_type', models.CharField(choices=[('U', 'From unique sequence'), ('C', 'From cluster of sequences')], max_length=1)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='clusters.sample')),
            ],
        ),
    ]
