# Generated by Django 4.1 on 2022-08-29 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clusters", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contig",
            name="assembly_type",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="technology",
        ),
    ]
