# Generated by Django 4.1 on 2022-11-12 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clusters", "0002_remove_contig_assembly_type_remove_sample_technology"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contig",
            name="igv_screenshot",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="igv_screenshot",
        ),
    ]
